### ISSUE TITLE
Unable to compile project due to dependency

### ISSUE THREAD

**Issue by bha2020** [Kaljurand/K6nele#54] opened 2018-03-13 12:11 UTC
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve project :speechutils:app. Open File Show Details

Unable to resolve dependency for ':app@release/compileClasspath': Could not resolve project :speechutils:app. Open File Show Details

Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve project :speechutils:app. Open File Show Details

**Comment by Kaljurand** [comment] 2018-03-15 11:48
Can you provide the commandline (or some other description) of how do you try to compile the project?

The error seems to be caused by the fact that the speechutils repository (a separate repository) is not properly cloned. K6nele includes it as a submodule (https://github.com/Kaljurand/K6nele/blob/master/.gitmodules). Normally, the build system should automatically pull this in.

This is possibly related to https://github.com/Kaljurand/K6nele/issues/49

**Comment by bha2020** [comment] 2018-03-15 12:26
Thank you for the reply.
When I download this project as zip then folders net-speech-api and speechutils are empty.
so the main projet is not able to find dependency when i opened project in android studio.

**Comment by Kaljurand** [comment] 2018-03-16 02:58
Yes, if you install via zip-files, then you need to download and unpack the dependencies (net-speech-api and speechutils) separately.

**Comment by bha2020** [comment] 2018-03-16 04:45
yes I have unziped that dependency but the dependency folder is null.Not having any contents

**Comment by Kaljurand** [comment] 2018-03-17 13:42
I need more details, e.g. what do you mean by "dependency folder"? Which version of Android Studio do you use?

**Comment by lhztop** [comment] 2019-01-21 02:35
@Kaljurand I met the same problem, becasue I run in windows and git clone with https.
after use ssh and with --recursive, problem is fixed.
so it's clone problem.
it can be marked as fixed.

**Comment by Kaljurand** [comment] 2019-01-21 22:32
@lhztop Thanks!

**Closed by Kaljurand** 2019-01-21 22:32 UTC
