### ISSUE TITLE
Speechutils documentation on pausing background audio

### ISSUE THREAD

**Issue by viju2008** [Kaljurand/K6nele#75] opened 2020-05-17 10:38 UTC
Hello ,

This is a very useful repo.

In the speechutils github repo there is a para that mentions pausing background audio. I have built the app and am using it with kaldi gstreamer.

However, the background notification audio is spoiing the accuracy of recognition. 

Can you please provide sample code on how to pause background audio or some hints pointing out where i have to look to implement pausing of background audio like whatsapp notifications when i have tapped microphone to start listening.

Regards ,

**Comment by Kaljurand** [comment] 2020-05-19 20:54
See the usage in https://github.com/Kaljurand/speechutils/blob/master/app/src/main/java/ee/ioc/phon/android/speechutils/service/AbstractRecognitionService.java#L186

**Comment by Kaljurand** [comment] 2020-05-19 20:57
Duplicate of https://github.com/Kaljurand/speechutils/issues/11

**Closed by Kaljurand** 2020-05-19 20:57 UTC
